### ISSUE TITLE
include samples via submodule to cut down on initial repo download

### ISSUE THREAD

**Issue by cheapRoc** [tidalcycles/Dirt#15]
The initial repo download is pretty big for a git project. Including the samples separately would help keep things organized and provide an optional way to not have to download them if a user BYOS's and doesn't need them. 

You could do the following.

1. Create a new repo on github called `Dirt-samples`.  
1. Place the sample library in the repo and push them up to Github.  
1. `git rm -rf samples/` to remove them from the main repo.  
1. Link the new sample repo inside the main `Dirt` repo by using a [git submodule](http://www.git-scm.com/book/en/Git-Tools-Submodules) by running...  
    `git submodule add https://github.com/yaxu/Dirt-samples.git samples`
1. Suggest to new users that they optionally download these by running...  
    `git clone --recursive https://github.com/yaxu/Dirt.git`
1. `echo "samples/ >> .gitignore` so that it stays clear of the main repo in the future.  
1. If the same `samples/` directory is used, current users won't be affected.  

Hope that gives you an option if you want to. Awesome project!

**Comment by lennart** [comment]
Though I am not a big fan of submodules I like the idea of not having to pull in all samples when cloning a fresh Dirt repository.

However one would also have to remove the objects from git history (http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects) since all clones will still download all the former samples since they are still reachable via history.

@yaxu If you are fine with the process, I'd be volunteering to move samples into a separate repo as shown above by @cheapRoc add them as a submodule and then prune the dirt history of the objects to cut down the size of the repository. Additionally I'd update the installation instructions (and e.g. the install.sh script for linux, as this should clone --recursive)

**Comment by yaxu** [comment]
That's be ace, thanks Lennart

**Comment by lennart** [comment]
@yaxu regarding this process, there's one thing which we (developers only) have to be aware of:

> Be warned: this technique is destructive to your commit history. It rewrites every commit object since the earliest tree you have to modify to remove a large file reference. If you do this immediately after an import, before anyone has started to base work on the commit, you’re fine – otherwise, you have to notify all contributors that they must rebase their work onto your new commits.

[as stated in the git book](http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects)

Text suggestion for lurk & README: remove all working copies and start with a new cloned [dirt github repo](https://github.com/tidalcycles/Dirt).

We might mark this change in a version bump, but as far as I know there is no versioning on dirt, yet.

I am working on this change right now, as I want to get dirt running on a raspberry pi 2 and I don't want to clone the whole sample library.

**Comment by lennart** [comment]
ok, I have a working dirt version recursively cloned from my fork:

```shell
git clone --recursive https://github.com/lennart/Dirt
```

without `--recursive` this takes only a few seconds. __Beware, these changes cannot be merged, history has been rewritten ;)__

**Comment by yaxu** [comment]
Hey @lennart,
Do you fancy making a pull request for this?

**Comment by lennart** [comment]
@yaxu I will have to push my current fork into another branch on the dirt repo and then replace the current master with my fork's master branch. Changes cannot be merged via pull request, since each commit has been rewritten to remove the binary files (this is git!)

I can do the aforementioned since I have the commit rights on the dirt repo, but it has to be accompained with an announcment for all dirt developers to reclone their local copies, since their git history is not compatible with the new one.

**Comment by yaxu** [comment]
Ok, sounds good..

**Comment by munshkr** [comment]
I think this is a good idea, and better be done with it now than later.

**Comment by kindohm** [comment]
No issue here. I'm ready.

**Comment by yaxu** [comment]
Ok, I'm holding on to my hat :)

**Comment by calumgunn** [comment]
DO IT!

**Comment by cheapRoc** [comment]
Good luck and God speed everyone... ;)

**Comment by yaxu** [comment]
Hit the button @lennart, we're psyched

**Comment by lennart** [comment]
ok, I'll just be rebasing the latest dirt commits and replace current master with my fork's master.

**Comment by lennart** [comment]
master is replaced. currently this only works with the --single-branch option on cloning, since there are other branches (including the oldmaster) that still contain the samples.

which of these are free to delete?

all remaining have to be rewritten as well…

I also pruned empty commits

**Comment by lennart** [comment]
my suggestion would be to delete all other branches, samples have their own home now and portaudio is already integrated (right?)

if you're ok with this I'd delete the other branches…

**Comment by yaxu** [comment]
Sounds good to me. Thanks @lennart !

**Comment by calumgunn** [comment]
Yup! Let's do this.

**Comment by lennart** [comment]
branches are out, I am also updating the installation instructions over at tidal.lurk.org so this change will stay backwards compatible for beginners (i.e. adds the --recursive option on clone)

for all others, cloning without `--recursive` should _soonish*_ result in only getting the _code_ and no samples at all.

*Currently the original branches seem to still be in the repository and it might take some time for github to garbage collect the repository and cut down its size.

**Comment by lennart** [comment]
last thing, I have to delete the 1.0 tag as well since it still refers to a commit that makes commits that contain samples reachable.

I'll be retagging the specific _commit_ in the new history again and push the tag upstream after that.

**Comment by lennart** [comment]
ok fast now…

please reopen this if there are any issues with the repo, but for now I guess this can be closed

**Comment by sbl** [comment]
> We might mark this change in a version bump, but as far as I know there is no versioning on dirt, yet.

There is already `1.0` tag why not make this into a 2.0.0 (or similar version that you prefer). 
I could in turn also update the homebrew formula https://github.com/Homebrew/homebrew/blob/master/Library/Formula/dirt.rb  to simplify the general installation process for osx users.

**Comment by calumgunn** [comment]
I feel a version bump would be good - in the scope of semantic versioning, is this a 'major' bump? http://semver.org/
Can't help feeling it should be minor... `1.1.0`?

**Comment by cheapRoc** [comment]
:+1: for keeping major and incrementing minor, 1.1.0
