### ISSUE TITLE
about `hit max sounds (512)`

### ISSUE THREAD

**Issue by seansay** [tidalcycles/Dirt#28]
is there any option to turn up the max sounds count?

**Comment by yaxu** [comment]
It's defined in audio.h
It would be better as a runtime option.

**Comment by seansay** [comment]
@yaxu 
do you incease this setting in your performance? just curious :smile:

**Comment by kindohm** [comment]
I change it to 2048

**Comment by seansay** [comment]
@kindohm 
thanks!I'll close the issue

**Comment by dfkettle** [comment]
Hi! I'd like to try adding a command-line option to increase this, similar to the option for specifying the number of "workers". Is anyone currently working on the same thing? If not, I'll go ahead and create a "fork".
