### ISSUE TITLE
ld: warning: directory not found for option '-L/opt/local/lib'

### ISSUE THREAD

**Issue by robjac** [tidalcycles/Dirt#35]
Hi everyone, just wanted to know if anyone is getting the same `warning` at `make dirt` ?

```
☁  Dirt [master] make dirt
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o dirt.o dirt.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o common.o common.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o audio.o audio.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o file.o file.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o server.o server.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o jobqueue.o jobqueue.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o thpool.o thpool.c
gcc -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN   -c -o jack.o jack.c
gcc dirt.o common.o audio.o file.o server.o jobqueue.o thpool.o jack.o -g -I/usr/local/include -I/opt/local/include -Wall -O3 -std=gnu99 -DJACK -DSCALEPAN -lm -L/usr/local/lib -L/opt/local/lib -llo -lsndfile -lsamplerate -lpthread -ljack -o dirt
ld: warning: directory not found for option '-L/opt/local/lib'
☁  Dirt [master]
```

I'd be happy to post my entire output from these instructions:

```
cabal update
cabal install tidal
cd ~/Dirt
(or wherever your Dirt folder is)
git pull
make clean
make dirt
```

everything seemed fine until the last command. 

Don't have time at the moment to check if tidal runs regardless of the warning. But will update here when I do. 

cheers,
-Robbie

**Comment by clample** [comment]
Hi Robjac,

I got this error installing dirt on mac. I was able to fix this issue by just creating the /opt/local/lib folder. Nothing was put in there, so it may also work to just remove -L/opt/local/lib from LDFAGS.

**Comment by yaxu** [comment]
Yes this is just a warning and nothing to be worried about. There must a good way to stop this warning being printed though so lets keep this issue open.

**Comment by brydavis** [comment]
Creating empty folder(s) worked, although I have to create all three...
`sudo mkdir /opt /opt/local /opt/local/lib`

**Comment by derekslenk** [comment]
@brydavis - next time you can do sudo mkdir -p /opt/local/lib  -p creates all the folders in the path that are missing

**Comment by imipolexg** [comment]
This is almost certainly because you have the environment variable `LIBRARY_PATH` set to include `/opt/local/lib`, for example if you installed macports but then uninstalled it later. Check your environment, (`echo $LIBRARY_PATH` or maybe `DYLD_LIBRARY_PATH` or `LD_LIBRARY_PATH` although I don't know if those are supported on macOS), track down where it's being set (probably `~/.profile` or `~/.bashrc` and remove the setting there.
