### ISSUE TITLE
./dirt: No such file or directory (mac, homebrew)

### ISSUE THREAD

**Issue by mrtunes** [tidalcycles/Dirt#40]
i made it to this step: 

cd ~/Dirt
./dirt &

and then i got the error: 
./dirt: No such file or directory

**Comment by yaxu** [comment]
Hey @mrtunes 
What happens if you do:
```
cd ~/Dirt
make clean
make
./dirt &
```

**Comment by mrtunes** [comment]
yep that did it. thanks!
