### ISSUE TITLE
Question: Was there a retag of the 1.0 release over the past year or so?

### ISSUE THREAD

**Issue by zmwangx** [tidalcycles/Dirt#57]
Dirt is packaged by [Homebrew](http://brew.sh), with its [package definition](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dirt.rb) (what we call a "formula") last updated last October, recording a SHA-256 checksum of c7c51ea3f279c048e84d988978455f075fd8ae063b2ad7378fc9b8369218f8fb for the tarball https://github.com/yaxu/Dirt/archive/1.0.tar.gz. However, we just noticed (https://github.com/Homebrew/homebrew-core/pull/2552) that the tarball now reports a different SHA-256 checksum of 4a79a3c8650e8852907beb2d40af0f9bc2824adcffc91041fe62edd55c23ecdc. I wonder if there was a retag since last October, and if so, why. Thanks for your time.

P.S. For packaging's sake, the project could also use a new release, if that's feasible for you.

**Comment by lennart** [comment]
we rebased the whole dirt tree to reduce repo size. I guess that's the reason the sha is different.

samples now live in https://github.com/tidalcycles/Dirt-Samples

they are a submodule of this repo, so if homebrew can clone recursively, installation shoukd stay the same.

regarding a new version, the old sha is now invalid so can one not simp,y replace it in the formula?

**Comment by zmwangx** [comment]
@lennart Thanks for the clarification.

> regarding a new version, the old sha is now invalid so can one not simp,y replace it in the formula?

I meant to say that the last release was from 2013 and there are 148 commits on master since that release, so cutting a new release could benefit users.

**Comment by lennart** [comment]
In the future [https://github.com/musikinformatik/SuperDirt] will replace Dirt as the default sampler for [Tiodalcycles](https://github.com/tidalcycles/Tidal) 

@yaxu can we simply make a consolidating release of Dirt bumping version without changes from current master and push a new tag?
